/**
 * Receipt Wrangler API.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Group member
 */
export interface GroupMember { 
    createdAt?: string;
    /**
     * Group compound primary key
     */
    groupId: number;
    /**
     * Id of the modern group role assigned to the member
     */
    groupRoleId?: number;
    updatedAt?: string;
    /**
     * User compound primary key
     */
    userId: number;
    /**
     * Category ids this individual member may see, narrowing WITHIN whatever their group role allows (the two layers intersect). Empty means the member adds no narrowing of their own: they fall back to the role\'s set, EXCEPT when the role sets requiresIndividualCategoryGrants, in which case an unassigned member sees no categories at all (fail closed). Read only here — write via PUT /group/{groupId}/member/{userId}/grants.
     */
    categoryGrants?: Array<number>;
    /**
     * Tag counterpart of categoryGrants. Restricted independently of categories.
     */
    tagGrants?: Array<number>;
}

