/**
 * Receipt Wrangler API.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ReceiptStatus } from './receiptStatus';
import { ReceiptSummaryPosition } from './receiptSummaryPosition';
import { QuickScanDefaultPaidByType } from './quickScanDefaultPaidByType';


export interface GroupReceiptSettings { 
    id: number;
    createdAt: string;
    createdBy?: number;
    /**
     * Created by entity\'s name
     */
    createdByString?: string;
    updatedAt?: string;
    /**
     * Group foreign key
     */
    groupId: number;
    /**
     * Hide receipt images
     */
    hideImages?: boolean;
    /**
     * Hide receipt categories
     */
    hideReceiptCategories?: boolean;
    /**
     * Hide receipt tags
     */
    hideReceiptTags?: boolean;
    /**
     * Hide receipt item categories
     */
    hideItemCategories?: boolean;
    /**
     * Hide receipt item tags
     */
    hideItemTags?: boolean;
    /**
     * Hide receipt comments
     */
    hideComments?: boolean;
    /**
     * Hide share categories
     */
    hideShareCategories?: boolean;
    /**
     * Hide share tags
     */
    hideShareTags?: boolean;
    /**
     * Show the paid by field in quick scan
     */
    quickScanPaidByEnabled?: boolean;
    /**
     * Require the paid by field in quick scan
     */
    quickScanPaidByRequired?: boolean;
    quickScanDefaultPaidByType?: QuickScanDefaultPaidByType;
    /**
     * Default paid by user id when paid by is optional and type is USER
     */
    quickScanDefaultPaidById?: number;
    /**
     * Show the status field in quick scan
     */
    quickScanStatusEnabled?: boolean;
    /**
     * Require the status field in quick scan
     */
    quickScanStatusRequired?: boolean;
    quickScanDefaultStatus?: ReceiptStatus;
    /**
     * Show the categories field in quick scan
     */
    quickScanCategoriesEnabled?: boolean;
    /**
     * Require the categories field in quick scan
     */
    quickScanCategoriesRequired?: boolean;
    /**
     * Show the tags field in quick scan
     */
    quickScanTagsEnabled?: boolean;
    /**
     * Require the tags field in quick scan
     */
    quickScanTagsRequired?: boolean;
    /**
     * Show the comment field in quick scan
     */
    quickScanCommentEnabled?: boolean;
    /**
     * Require the comment field in quick scan
     */
    quickScanCommentRequired?: boolean;
    /**
     * Custom field ids that are pre-added to every receipt created for this group. Always present; an empty array means the group has configured none. Read only here - write via UpdateGroupReceiptSettingsCommand.defaultCustomFieldIds.
     */
    defaultCustomFieldIds?: Array<number>;
    /**
     * Also attach the group\'s default custom fields to receipts the SERVER creates (quick scan, email integration). Off by default.
     */
    applyDefaultCustomFieldsOnIngest?: boolean;
    /**
     * Show the block of totals under this group\'s receipts table. Off by default, so an existing install is unchanged until an admin opts in.
     */
    receiptSummaryEnabled?: boolean;
    /**
     * CURRENCY custom field ids totalled in the receipt summary, in the order their columns are rendered. Always present; an empty array means the group totals only the receipt amount. Read only here - write via UpdateGroupReceiptSettingsCommand.receiptSummaryCustomFieldIds.
     */
    receiptSummaryCustomFieldIds?: Array<number>;
    /**
     * Receipt statuses broken out as their own row in the receipt summary, in ReceiptStatus declaration order. A configured status matching no receipt still renders, as a zero row. Always present; an empty array means the summary shows only the overall row. Read only here - write via UpdateGroupReceiptSettingsCommand.receiptSummaryStatuses.
     */
    receiptSummaryStatuses?: Array<ReceiptStatus>;
    receiptSummaryPosition?: ReceiptSummaryPosition;
}
export namespace GroupReceiptSettings {
}


