/**
 * Receipt Wrangler API.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ReceiptPagedRequestFilter } from './receiptPagedRequestFilter';


export interface ReceiptSummaryCommand { 
    filter?: ReceiptPagedRequestFilter;
    /**
     * The group whose receipt settings shape the breakdown. Exists for the synthetic \"All\" group, which spans every group the caller belongs to and so has no meaningful settings of its own - the client picks which member group\'s configuration to apply. OMIT it for a real group, where the group in the path is used. The DATA is always the path group\'s filtered set; this only chooses the shape of the breakdown. A group the caller cannot read is a 403.
     */
    configurationGroupId?: number;
}

