/**
 * Receipt Wrangler API.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Where a group\'s receipt summary renders relative to its receipts list. A client that meets a value added later must degrade to BOTTOM, which is where the block rendered before the setting existed, rather than failing the whole payload.
 */
export type ReceiptSummaryPosition = 'TOP' | 'BOTTOM';

export const ReceiptSummaryPosition = {
    Top: 'TOP' as ReceiptSummaryPosition,
    Bottom: 'BOTTOM' as ReceiptSummaryPosition
};

