/**
 * Receipt Wrangler API.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ReceiptSummaryRow } from './receiptSummaryRow';
import { ReceiptSummaryPosition } from './receiptSummaryPosition';


export interface ReceiptSummary { 
    /**
     * Whether the configuration group has the summary turned on. False comes back at a normal 200 with zeroed rows, so a client with stale group settings renders nothing rather than surfacing an error.
     */
    enabled: boolean;
    /**
     * The group whose settings produced this breakdown
     */
    configurationGroupId: number;
    position: ReceiptSummaryPosition;
    overall: ReceiptSummaryRow;
    /**
     * One row per configured status, in ReceiptStatus declaration order. A configured status matching no receipt is still present, with zeroed figures. Always present; empty when no status is configured.
     */
    statuses: Array<ReceiptSummaryRow>;
}
export namespace ReceiptSummary {
}


