/**
 * Receipt Wrangler API.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ReceiptRequirements { 
    /**
     * At least one comment is required on the group\'s receipts
     */
    commentRequired: boolean;
    /**
     * At least one image is required on the group\'s receipts
     */
    imageRequired: boolean;
}

