/**
 * Receipt Wrangler API.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ReceiptSummaryCustomFieldTotal } from './receiptSummaryCustomFieldTotal';
import { ReceiptStatus } from './receiptStatus';


export interface ReceiptSummaryRow { 
    status: ReceiptStatus;
    /**
     * How many receipts this row covers. On the overall row this matches the table\'s own total count for the same filter.
     */
    receiptCount: number;
    /**
     * Sum of the receipts\' amounts
     */
    total: string;
    /**
     * One entry per configured currency custom field, in the configured order. Always present; empty when the group totals only the receipt amount.
     */
    customFieldTotals: Array<ReceiptSummaryCustomFieldTotal>;
}
export namespace ReceiptSummaryRow {
}


