/**
 * Receipt Wrangler API.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ReceiptSummaryCustomFieldTotal { 
    customFieldId: number;
    /**
     * The custom field\'s name, so the client needs no second lookup
     */
    name: string;
    /**
     * Sum of this field\'s currency values across the row\'s receipts
     */
    total: string;
}

