/**
 * Receipt Wrangler API.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type RecognitionTaskStage = 'UPLOAD' | 'PREPROCESSING' | 'OCR' | 'AI' | 'PARSING' | 'SAVING' | 'DONE';

export const RecognitionTaskStage = {
    Upload: 'UPLOAD' as RecognitionTaskStage,
    Preprocessing: 'PREPROCESSING' as RecognitionTaskStage,
    Ocr: 'OCR' as RecognitionTaskStage,
    Ai: 'AI' as RecognitionTaskStage,
    Parsing: 'PARSING' as RecognitionTaskStage,
    Saving: 'SAVING' as RecognitionTaskStage,
    Done: 'DONE' as RecognitionTaskStage
};

