/**
 * Receipt Wrangler API.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ReportColumn } from './reportColumn';
import { ReportDetail } from './reportDetail';
import { ReportDocument } from './reportDocument';
import { ReportPeriod } from './reportPeriod';
import { ReceiptPagedRequestFilter } from './receiptPagedRequestFilter';


export interface ReportRequestCommand { 
    /**
     * Report name; used for the download filename
     */
    name?: string;
    /**
     * Ids of the groups the report covers
     */
    groupIds: Array<string>;
    period: ReportPeriod;
    /**
     * Which receipts go into the report
     */
    filter?: ReceiptPagedRequestFilter;
    /**
     * Ordered engine field keys to nest the report by
     */
    groupBy?: Array<string>;
    /**
     * Column-heading overrides for the grouping levels, keyed by the groupBy field key. A key that is absent, blank, or not present in groupBy falls back to the field catalog\'s label.
     */
    groupByLabels?: { [key: string]: string; };
    detail: ReportDetail;
    columns: Array<ReportColumn>;
    /**
     * Emit a subtotal row at each grouping level
     */
    subtotals?: boolean;
    /**
     * Emit one grand-total row across everything
     */
    grandTotals?: boolean;
    document?: ReportDocument;
    /**
     * One or more output formats; multiple are zipped together
     */
    formats: Array<ReportRequestCommand.FormatsEnum>;
}
export namespace ReportRequestCommand {
    export type FormatsEnum = 'csv' | 'xlsx' | 'pdf';
    export const FormatsEnum = {
        Csv: 'csv' as FormatsEnum,
        Xlsx: 'xlsx' as FormatsEnum,
        Pdf: 'pdf' as FormatsEnum
    };
}


