/**
 * Receipt Wrangler API.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Permission } from './permission';
import { ReportTemplateGrant } from './reportTemplateGrant';
import { PermissionScope } from './permissionScope';


export interface Role { 
    id: number;
    name: string;
    description?: string;
    scope: PermissionScope;
    /**
     * Whether this role is the default for its scope — assigned to new accounts (APP) or to group creators (GROUP). Exactly one role per scope is the default.
     */
    isDefault: boolean;
    isSystem: boolean;
    permissions: Array<Permission>;
    /**
     * Number of users or group members currently assigned this role
     */
    assignedCount?: number;
    /**
     * Category ids a GROUP role restricts its members to. Empty means unrestricted (members may use every category). Always empty for app roles.
     */
    categoryGrants?: Array<number>;
    /**
     * Tag ids a GROUP role restricts its members to. Empty means unrestricted (members may use every tag). Always empty for app roles.
     */
    tagGrants?: Array<number>;
    /**
     * User ids whose receipts a GROUP role lets its members see (by the receipt\'s \"paid by\" user). Empty with includeOwnPaidReceipts false means unrestricted (members see every payer\'s receipts). Always empty for app roles.
     */
    paidByUserGrants?: Array<number>;
    /**
     * Whether a GROUP role lets each member see receipts they paid for. Part of the paid-by visibility filter; always false for app roles.
     */
    includeOwnPaidReceipts?: boolean;
    /**
     * Whether a GROUP role exempts its members from member-presence isolation (they see, and are seen by, every member of an isolated group). Always false for app roles.
     */
    seesAllMembers?: boolean;
    /**
     * Whether users created with this APP role skip the automatic personal \"My Receipts\" group. The virtual \"All\" group is always created. Applies at user-creation time only — changing it never adds or removes a group for an existing user. Always false for group roles.
     */
    skipDefaultGroupCreation?: boolean;
    /**
     * Whether a GROUP role requires per-member category assignment. When true, a member holding this role with no individual category grants sees NO categories, rather than falling back to the role\'s set. Always false for app roles.
     */
    requiresIndividualCategoryGrants?: boolean;
    /**
     * Tag counterpart of requiresIndividualCategoryGrants. Always false for app roles.
     */
    requiresIndividualTagGrants?: boolean;
    /**
     * Whether a GROUP role requires its members to keep at least one comment on the group\'s receipts (waived when the group hides comments or the member lacks group.comments.create). Always false for app roles.
     */
    requireReceiptComment?: boolean;
    /**
     * Whether a GROUP role requires its members to keep at least one image on the group\'s receipts (waived when the group hides images). Always false for app roles.
     */
    requireReceiptImage?: boolean;
    /**
     * Per-template action grants restricting which report templates a GROUP role\'s members may act on. Empty means unrestricted (every template the role\'s group access reaches). Always empty for app roles.
     */
    reportTemplateGrants?: Array<ReportTemplateGrant>;
}
export namespace Role {
}


