/**
 * Receipt Wrangler API.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SystemTaskSourceFileView { 
    /**
     * The upload\'s original file name
     */
    name: string;
    /**
     * Base64 encoded image, converted for display
     */
    encodedImage: string;
}

