/**
 * Receipt Wrangler API.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Per-member category/tag assignment. The membership being edited is taken from the URL, never this body.
 */
export interface UpdateGroupMemberGrantsCommand { 
    /**
     * Category ids to assign to this member. Every id must sit within the ceiling set by the member\'s group role, or the request is rejected with 400; duplicate ids are rejected with 400 as well. An empty array clears the member\'s category restriction — handing them back to their role\'s set, or, when the role sets requiresIndividualCategoryGrants, leaving them with no categories at all (fail closed).
     */
    categoryGrants?: Array<number>;
    /**
     * Tag counterpart of categoryGrants.
     */
    tagGrants?: Array<number>;
}

