/**
 * Receipt Wrangler API.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpsertCustomFieldOptionCommand { 
    /**
     * Id of an existing option to update. Omit it (or send 0) to add a new option. Options are never removed by an update.
     */
    id?: number;
    /**
     * Custom Field Option value
     */
    value?: string;
    /**
     * Custom Field Id
     */
    customFieldId: number;
}

